before_script:
  # Create 'sudouser' w/ sudo password & perms on Travis' homedir
  - inv travis.make-sudouser
script:
  # Execute full test suite + coverage, as the new sudo-capable user
  - inv travis.sudo-coverage
  # Perform extra "not feasible inside pytest for no obvious reason" tests
  - inv regression
  # Websites build OK? (Not on PyPy3, Sphinx is all "who the hell are you?" =/
  - "if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then inv sites; fi"
  # Doctests in websites OK? (Same caveat as above...)
  - "if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then inv www.doctest; fi"
  # Did we break setup.py?
  # NOTE: sometime in 2019 travis grew a bizarre EnvironmentError problem
  # around inability to overwrite/remote __pycache__ dirs...this attempts to
  # workaround
  - "find . -type d -name __pycache__ | sudo xargs rm -rf"
  - inv travis.test-installation --package=invoke --sanity="inv --list"
  # Test distribution builds, including some package_data based stuff
  # (completion script printing)
  - "inv travis.test-packaging --package=invoke --sanity='inv --list && inv --print-completion-script zsh' --alt-python=alt_env/bin/python"
#after_success:
  # Upload coverage data to codecov
  # NOTE: commented out because something here is resulting in inaccurate
  # coverage stats, eg 75% when it's really 95%! Fix on Circle.
  #- codecov
notifications:
  irc:
    channels: "irc.freenode.org#invoke"
    template:
      - "%{repository_name}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
    on_error: change
  email: false
