version: 2.1


orbs:
  orb: invocations/orb@1.0.4


jobs:
  integration:
    executor:
      name: orb/default
      version: "3.6"
    steps:
      - orb/setup
      - run: inv ci.make-sudouser
      - run: inv ci.sudo-run 'inv integration'
      - orb/debug


workflows:
  main:
    jobs:
      - orb/lint:
          name: Lint
      - orb/format:
          name: Style check
      - orb/coverage:
          name: Test 3.6
      - integration:
          name: Integration tests
      - orb/test-release:
          name: Release test
      - orb/test:
          name: Test << matrix.version >>
          requires: ["Test 3.6"]
          matrix:
            parameters:
              version: ["3.7", "3.8", "3.9"]
      - orb/docs:
          name: "Docs"
          requires: ["Test 3.6"]
