version: 2.1


orbs:
  orb: invocations/orb@1.0.4

workflows:
  main:
    jobs:
      - orb/lint:
          name: Lint
      - orb/format:
          name: Style check
      - orb/coverage:
          name: Test 3.6
      - orb/test-release:
          name: Release test
      - orb/test:
          name: Test << matrix.version >>
          requires: ["Test 3.6"]
          matrix:
            parameters:
              version: ["3.7", "3.8", "3.9"]
      - orb/docs:
          name: "Docs"
          requires: ["Test 3.6"]
